### ISSUE TITLE
Feature Request: Show context information

### ISSUE THREAD

**Issue by Echsecutor** [european-epc-competence-center/vc-verifier#18]
The JSON-LD Context provides a URL to explain what each attribute means. It would be nice to have some UI access to this link next to the attrbbutes. (something like anchor + href at atribute, (?) bubble, ...)

**Comment by F-Node-Karlsruhe** [comment]
Started in branch https://github.com/european-epc-competence-center/vc-verifier/tree/show-credential-context

**Comment by F-Node-Karlsruhe** [comment]
Closed with https://github.com/european-epc-competence-center/vc-verifier/commit/a2b2c291feed32e5dcaa11c3d4dd29fc5388ffa9
